config/routes.rb
Rails.application.routes.draw do

  root "tasks#index"
  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base

  validates :task, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path, notice: "Your task has successfully been created"
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(task_params)
      redirect_to tasks_path, notice: "Your task has successfully been updated"
    else
      redirect_to :back, notice: "There was an error updating your task"
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice: "Your task has successfully been deleted"
  end

  private

  def task_params
    params.require(:task).permit(:task)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, message| %>
  <%= content_tag :div, message, id:"flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <%= f.label :task %>
  <%= f.text_field :task %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h2>Original Task:</h2>

<!-- <p><%= @task.task %></p> -->

<h2>Update:</h2>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<%= render 'form' %>

<ul>
<% @tasks.each do |t| %>
  <li id="task_<%= t.id %>">
    <%= t.task %><br>
    <%= link_to 'Edit', edit_task_path(t) %>
    <%= link_to 'Delete', t, method: :delete %>
    </li>
<% end %>
</ul>